export const DEFAULT_SETTINGS = {
  websiteName: 'HOSTEL HELPER',
  ownerName: 'K ROHIT KUMAR',
  location: 'SRM AP',
  whatsappNumber: '6300141729',
  description: 'Quickly request deliveries, laundry services and hostel shop items.',
};

export const INITIAL_SECTIONS_DATA = [
  {
    slug: 'gate-delivery',
    name: 'GATE DELIVERY',
    description: 'Get your outside orders delivered from the hostel gate.',
    icon: 'DoorClosed',
    displayOrder: 1,
    isActive: true,
    forms: [
      {
        slug: 'food',
        name: 'FOOD',
        description: 'Order food delivery pickup from hostel gate',
        icon: 'Utensils',
        submitButtonText: 'SUBMIT FOOD REQUEST',
        whatsappFormat: 'HOSTEL HELPER - FOOD REQUEST',
        displayOrder: 1,
        isActive: true,
        fields: [
          {
            label: 'Item Name',
            fieldName: 'itemName',
            fieldType: 'text',
            placeholder: 'e.g. Biryani, Pizza, Burger',
            isRequired: true,
            displayOrder: 1,
          },
          {
            label: 'Quantity',
            fieldName: 'quantity',
            fieldType: 'number',
            placeholder: 'e.g. 1, 2, 3',
            isRequired: true,
            displayOrder: 2,
          },
          {
            label: 'Price',
            fieldName: 'price',
            fieldType: 'text',
            placeholder: 'e.g. ₹250',
            isRequired: true,
            displayOrder: 3,
          },
          {
            label: 'Restaurant Name',
            fieldName: 'restaurantName',
            fieldType: 'text',
            placeholder: 'e.g. Domino\'s, Mehfil, Cafe Coffee Day',
            isRequired: true,
            displayOrder: 4,
          },
          {
            label: 'Contact Number',
            fieldName: 'contactNumber',
            fieldType: 'phone',
            placeholder: 'e.g. 9876543210',
            isRequired: true,
            displayOrder: 5,
          },
          {
            label: 'Additional Details',
            fieldName: 'additionalDetails',
            fieldType: 'textarea',
            placeholder: 'Any special instructions or gate details...',
            isRequired: false,
            displayOrder: 6,
          },
        ],
      },
      {
        slug: 'bigbasket',
        name: 'BIGBASKET',
        description: 'BigBasket grocery parcel pickup from gate',
        icon: 'ShoppingBag',
        submitButtonText: 'SUBMIT BIGBASKET REQUEST',
        whatsappFormat: 'HOSTEL HELPER - BIGBASKET REQUEST',
        displayOrder: 2,
        isActive: true,
        fields: [
          {
            label: 'Item Name',
            fieldName: 'itemName',
            fieldType: 'text',
            placeholder: 'e.g. Grocery essentials / Fruits & Snacks',
            isRequired: true,
            displayOrder: 1,
          },
          {
            label: 'Price',
            fieldName: 'price',
            fieldType: 'text',
            placeholder: 'e.g. ₹540',
            isRequired: true,
            displayOrder: 2,
          },
          {
            label: 'Item Details',
            fieldName: 'itemDetails',
            fieldType: 'textarea',
            placeholder: 'Brief summary of items in parcel...',
            isRequired: true,
            displayOrder: 3,
          },
          {
            label: 'Quantity / Amount',
            fieldName: 'quantityOrAmount',
            fieldType: 'text',
            placeholder: 'e.g. 2 bags or 5 items',
            isRequired: true,
            displayOrder: 4,
          },
          {
            label: 'Contact Number',
            fieldName: 'contactNumber',
            fieldType: 'phone',
            placeholder: 'e.g. 9876543210',
            isRequired: true,
            displayOrder: 5,
          },
          {
            label: 'Additional Details',
            fieldName: 'additionalDetails',
            fieldType: 'textarea',
            placeholder: 'Delivery slot or gate instructions...',
            isRequired: false,
            displayOrder: 6,
          },
        ],
      },
      {
        slug: 'online-order',
        name: 'ONLINE ORDER',
        description: 'Amazon, Flipkart, Myntra parcel pickup',
        icon: 'Package',
        submitButtonText: 'SUBMIT ONLINE ORDER',
        whatsappFormat: 'HOSTEL HELPER - ONLINE ORDER',
        displayOrder: 3,
        isActive: true,
        fields: [
          {
            label: 'Item Name',
            fieldName: 'itemName',
            fieldType: 'text',
            placeholder: 'e.g. Books, Shoes, Electronics',
            isRequired: true,
            displayOrder: 1,
          },
          {
            label: 'Delivered From',
            fieldName: 'deliveredFrom',
            fieldType: 'text',
            placeholder: 'e.g. Amazon, Flipkart, Myntra, Bluedart',
            isRequired: true,
            displayOrder: 2,
          },
          {
            label: 'Delivery Time',
            fieldName: 'deliveryTime',
            fieldType: 'text',
            placeholder: 'e.g. Today 4:00 PM, or OTP pending',
            isRequired: true,
            displayOrder: 3,
          },
          {
            label: 'Price',
            fieldName: 'price',
            fieldType: 'text',
            placeholder: 'e.g. Paid online or COD ₹399',
            isRequired: true,
            displayOrder: 4,
          },
          {
            label: 'Contact Number',
            fieldName: 'contactNumber',
            fieldType: 'phone',
            placeholder: 'e.g. 9876543210',
            isRequired: true,
            displayOrder: 5,
          },
          {
            label: 'Additional Details',
            fieldName: 'additionalDetails',
            fieldType: 'textarea',
            placeholder: 'Tracking ID, courier name, or special instructions...',
            isRequired: false,
            displayOrder: 6,
          },
        ],
      },
    ],
  },
  {
    slug: 'laundry',
    name: 'LAUNDRY',
    description: 'Submit and manage your hostel laundry request.',
    icon: 'Shirt',
    displayOrder: 2,
    isActive: true,
    forms: [
      {
        slug: 'laundry-request',
        name: 'LAUNDRY REQUEST',
        description: 'Submit your hostel laundry collection and wash request',
        icon: 'Shirt',
        submitButtonText: 'SUBMIT LAUNDRY REQUEST',
        whatsappFormat: 'HOSTEL HELPER - LAUNDRY REQUEST',
        displayOrder: 1,
        isActive: true,
        fields: [
          {
            label: 'Laundry Bag Color',
            fieldName: 'bagColor',
            fieldType: 'text',
            placeholder: 'e.g. Blue, Red, Black, Green',
            isRequired: true,
            displayOrder: 1,
          },
          {
            label: 'Application Number',
            fieldName: 'applicationNumber',
            fieldType: 'text',
            placeholder: 'e.g. AP21110010001',
            isRequired: true,
            displayOrder: 2,
          },
          {
            label: 'Student Name',
            fieldName: 'studentName',
            fieldType: 'text',
            placeholder: 'e.g. Rohit Kumar',
            isRequired: true,
            displayOrder: 3,
          },
          {
            label: 'QR Number',
            fieldName: 'qrNumber',
            fieldType: 'text',
            placeholder: 'e.g. QR-8849',
            isRequired: true,
            displayOrder: 4,
          },
          {
            label: 'Basement Contact Number',
            fieldName: 'basementContact',
            fieldType: 'phone',
            placeholder: 'e.g. 9876543210',
            isRequired: true,
            displayOrder: 5,
          },
          {
            label: 'Additional Details',
            fieldName: 'additionalDetails',
            fieldType: 'textarea',
            placeholder: 'Number of cloths, delicate items, or specific instructions...',
            isRequired: false,
            displayOrder: 6,
          },
        ],
      },
    ],
  },
  {
    slug: 'shops',
    name: 'SHOPS',
    description: 'Request items from available hostel shops.',
    icon: 'Store',
    displayOrder: 3,
    isActive: true,
    forms: [
      {
        slug: 'total-fresh',
        name: 'TOTAL FRESH',
        description: 'Order fresh juices, dairy, fruits and snacks from Total Fresh',
        icon: 'Store',
        submitButtonText: 'SUBMIT SHOP REQUEST',
        whatsappFormat: 'HOSTEL HELPER - SHOP REQUEST',
        displayOrder: 1,
        isActive: true,
        fields: [
          {
            label: 'Item Name',
            fieldName: 'itemName',
            fieldType: 'text',
            placeholder: 'e.g. Milk packet, Banana smoothie, Bread',
            isRequired: true,
            displayOrder: 1,
          },
          {
            label: 'Quantity',
            fieldName: 'quantity',
            fieldType: 'text',
            placeholder: 'e.g. 2 packs, 500ml',
            isRequired: true,
            displayOrder: 2,
          },
          {
            label: 'Contact Number',
            fieldName: 'contactNumber',
            fieldType: 'phone',
            placeholder: 'e.g. 9876543210',
            isRequired: true,
            displayOrder: 3,
          },
          {
            label: 'Additional Details',
            fieldName: 'additionalDetails',
            fieldType: 'textarea',
            placeholder: 'Room number, hostel block, or substitute preference...',
            isRequired: false,
            displayOrder: 4,
          },
        ],
      },
    ],
  },
];
